---
- name: download HBase
  get_url: url="http://apache-mirror.rbc.ru/pub/apache/hbase/{{ hbase_version }}/hbase-{{ hbase_version }}{{ hadoop_suffix }}-bin.tar.gz" dest=/root/hbase-{{ hbase_version }}{{ hadoop_suffix }}-bin.tar.gz
  ignore_errors: true
  register: result

- name: try to get hbase from archive site if original one returns 404
  get_url: url="http://archive.apache.org/dist/hbase/{{ hbase_version }}/hbase-{{ hbase_version }}{{ hadoop_suffix }}-bin.tar.gz" dest=/root/hbase-{{ hbase_version }}{{ hadoop_suffix }}-bin.tar.gz
  when: result.failed and result.status_code is defined and result.status_code == 404

- name: unpack HBase
  command: bash -c "cd /opt && tar xzf /root/hbase-{{ hbase_version }}{{ hadoop_suffix }}-bin.tar.gz" creates=/opt/hbase-{{ hbase_version }}{{ hadoop_suffix }}

- name: create {{ hbase_distr_prefix }}
  shell: cp -r /opt/hbase-{{ hbase_version }}{{ hadoop_suffix }} {{ hbase_distr_prefix }} creates={{ hbase_distr_prefix }}

- name: add Hadoop user
  user: name={{ hadoop_user }} shell=/usr/sbin/nologin state=present

- name: make {{ hbase_var_prefix }}
  file: path={{ hbase_var_prefix }} state=directory owner={{ hadoop_user }} group={{ hadoop_user }} mode=0700

- name: make {{ hbase_distr_prefix }}/conf
  file: path={{ hbase_distr_prefix }}/conf state=directory owner=root group=root mode=0755

- name: put {{ hbase_distr_prefix }}/conf/hbase-site.xml
  template: src=hbase/hbase-site.xml dest={{ hbase_distr_prefix }}/conf/hbase-site.xml owner=root group=root mode=0644 backup=yes
  register: hbase_site_xml
  when: not hbase_standalone

- name: put {{ hbase_distr_prefix }}/conf/hbase-env.sh
  template: src=hbase/hbase-env.sh dest={{ hbase_distr_prefix }}/conf/hbase-env.sh owner=root group=root mode=0644 backup=yes

- name: create {{ hbase_distr_prefix }}/conf/hdfs-site.xml
  file: state=link src={{ hadoop_distr_prefix }}/conf/hdfs-site.xml dest={{ hbase_distr_prefix }}/conf/hdfs-site.xml
  when: not hbase_standalone

- name: create {{ hbase_distr_prefix }}/conf/core-site.xml
  file: state=link src={{ hadoop_distr_prefix }}/conf/core-site.xml dest={{ hbase_distr_prefix }}/conf/core-site.xml
  when: not hbase_standalone

- name: create {{ hbase_distr_prefix }}/conf/hadoop-metrics.properties
  file: state=link src={{ hadoop_distr_prefix }}/conf/hadoop-metrics.properties dest={{ hbase_distr_prefix }}/conf/hadoop-metrics.properties
  when: not hbase_standalone

- name: put {{ hbase_distr_prefix }}/conf/jmxremote.access
  template: src=hbase/jmxremote.access dest={{ hbase_distr_prefix }}/conf/jmxremote.access owner=root group=root mode=0644 backup=yes

- name: put {{ hbase_distr_prefix }}/conf/jmxremote.passwd
  template: src=hbase/jmxremote.passwd dest={{ hbase_distr_prefix }}/conf/jmxremote.passwd owner={{ hadoop_user }} group={{ hadoop_user }} mode=0600 backup=yes

# - name: dirty start for a standalone hbase
#   shell: /opt/hbase/bin/start-hbase.sh
#   when: hbase_standalone
#   register: hbase_start
#   failed_when: "'master running as process' not in hbase_start.stdout and 'starting master' not in hbase_start.stdout"
#   changed_when: "'starting master' in hbase_start.stdout"

- name: put hbase-master eye config file
  template: src=hbase/hbase-standalone.rb dest=/etc/eye/hbase-standalone.rb owner=root group=root mode=0644 backup=yes
  when: hbase_standalone
  tags: eye

- name: load config in eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye l /etc/eye/apps.eye"
  sudo: yes
  when: hbase_standalone
  tags: eye

- name: increase limits
  template: dest=/etc/security/limits.d/90-hbase.conf src=security/limits.d/90-hbase.conf backup=yes
  register: ulimit_conf
  tags: ulimit

- name: update ulimit
  lineinfile:
      dest: /etc/pam.d/common-session
      regexp: '^\s{0,}session\s{1,}required\s{1,}pam_limits.so'
      line: 'session required  pam_limits.so'
  tags: ulimit
  when: "ansible_os_family == 'Debian'"
      
  
# - name: update ulimit
#   shell: ulimit -n 65536
#   # sudo_user: hadoop
#   # when: ulimit_conf.changed
#   tags: ulimit

- name: create {{ hbase_distr_prefix }}/lib/native
  file: state=directory dest={{ hbase_distr_prefix }}/lib/native

- name: create {{ hbase_distr_prefix }}/lib/native/Linux-amd64-64
  file: state=directory dest={{ hbase_distr_prefix }}/lib/native/Linux-amd64-64

- name: make a link to libhadoop.so
  file: state=link src={{ hadoop_distr_prefix }}/lib/native/libhadoop.so dest={{ hbase_distr_prefix }}/lib/native/Linux-amd64-64/libhadoop.so
  when: not hbase_standalone

- name: make a link to libhdfs.so
  file: state=link src={{ hadoop_distr_prefix }}/lib/native/libhdfs.so dest={{ hbase_distr_prefix }}/lib/native/Linux-amd64-64/libhdfs.so
  when: not hbase_standalone
